// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testapi.Data;

#nullable disable

namespace testapi.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20240607110605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("testapi.Models.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("teamOneName")
                        .HasColumnType("TEXT");

                    b.Property<string>("teamTwoName")
                        .HasColumnType("TEXT");

                    b.Property<int>("winner")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
